config/routes.rb
Rails.application.routes.draw do
  get '/dashboard', to: "dashboard#index", as: "dashboard"
  get '/dashboard/user/:id', to: "dashboard#user", as: "user_dashboard"

  devise_for :admin_users
  resources :timelogs
  root 'landing#index'
  resource :users
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/timelog.rb
class Timelog < ActiveRecord::Base
  belongs_to :user
  validate :validate_per_day
  before_save :mark_is_late_and_login_time
  
  def self.nos_of_late_users_today
    where("DATE(created_at) = ?", Date.today).where(is_late: true).count
  end

  def self.user_stats(user_id)
    {avg_time: avg_time(self.where(user_id: user_id))}
  end
  def self.avg_time(data)
    times = data.collect {|t| (t.login_time.strftime("%H").to_i * 60) + t.login_time.strftime("%M").to_i}
    hours = ((times.sum/times.length)/60)
    minutes = ((times.sum/times.length)/60.0)
    minutes = (((minutes-hours)*60)).round
    "#{hours}:#{minutes.to_s.rjust(2, '0')}"
  end

  def self.stats
    {nos_of_late_users_today: nos_of_late_users_today, avg_time: avg_time_for_all_users}
  end

  def self.avg_time_for_all_users
    avg_time(Timelog.where(login_time: Date.today.beginning_of_day..Date.today.end_of_day))
  end

  def self.chart_data(user_id = nil)
    if user_id
      data = select("count(*) as y, is_late").where(user_id: user_id).group(:is_late)
    else
      data = select("count(*) as y, is_late").group(:is_late)
    end
    format_data(data)
  end

  def self.format_data(data)
    _data = []
    data.each do |d|
      _data << {name: "On time", y: d.y} unless d.is_late
      _data << {name: "Late", y: d.y} if d.is_late
    end
    _data
  end

  private
  def mark_is_late_and_login_time
    t = Time.now
    self.is_late = t.strftime("%H%M").to_i > 1000
    self.login_time = t
  end
  
  def validate_per_day
    present_today = Timelog.where(user_id: self.user_id).where("DATE(created_at) = ?", Date.today).count
    if present_today <= 0
      return true
    else
      self.errors.add(:base, "You are already logged in for today")
      return false
    end 
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :timelogs, dependent: :destroy
  validates :name, presence: true, uniqueness: true, format: {with: /\A[a-zA-Z]*\z/, message: "no special characters or numbder, only letters"}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_admin_user!
  def index
    @stats = Timelog.stats
    @timelogs = Timelog.joins(:user).select("*, users.name as username").paginate(:page => params[:page], :per_page => 10).order("users.name asc, login_time desc")
    @chart_data = Timelog.chart_data
  end
  def user
    @stats = Timelog.user_stats(params[:id])
    @timelogs = Timelog.where(user_id: params[:id]).paginate(:page => params[:page], :per_page => 10)
    @user = User.find(params[:id])
    @chart_data = Timelog.chart_data(@user.id)
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
    @timelog = Timelog.new
  end
end

app/controllers/timelogs_controller.rb
class TimelogsController < ApplicationController
  before_action :set_timelog, only: [:show, :edit, :update, :destroy]
  before_action :find_user
  # GET /timelogs/new
  def new
    @timelog ||= Timelog.new
  end

  # POST /timelogs
  # POST /timelogs.json
  def create
    @timelog = @user.timelogs.build(timelog_params)
    respond_to do |format|
      if @timelog.save
        format.html { redirect_to root_url, flash: flash_error}
        format.json { render :show, status: :created, location: @timelog }
      else
        format.html { redirect_to root_url, flash: base_error}
        format.json { render json: @timelog.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_timelog
      @timelog = Timelog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def timelog_params
      params.fetch(:timelog, {}).permit(:user_id, :login_time).merge({user_id: @user_id})
    end

    def find_user
      @user = User.find_by_name(params[:username])
      return true if @user
      flash[:error] = "User Not found"
      redirect_to :back
    end

    def flash_error
      return {error: "Hey you are late."} if @timelog.is_late
      return {notice: "Wow you are on time."}
    end

    def base_error
      error = @timelog.errors
      return {error: error[:base].first} if error && error[:base]
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :init_timelog
  before_action :authenticate_admin_user!, only: [:destroy]

  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to root_url, flash: {notice: 'User was successfully created.'} }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { redirect_to root_url, flash: {error: @user.errors.full_messages.join(', ')}}
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user = User.find_by(id:params[:format])
    if @user.destroy
      redirect_to dashboard_path, notice: 'User was successfully deleted.'
    else
      redirect_to dashboard_path, notice: "No user found"
      render json: @user.errors, status: :unprocessable_entity 
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.fetch(:user, {}).permit(:name)
    end

    def init_timelog
      @timelog = Timelog.new
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/timelogs_helper.rb
module TimelogsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/_charts.html.haml
%script{:src => "https://code.highcharts.com/highcharts.js"}
%script{:src => "https://code.highcharts.com/modules/exporting.js"}

.row
  .col-sm-6
    #container{:style => "min-width: 310px; height: 400px; max-width: 600px; margin: 0 auto"}

:javascript
    
     Highcharts.chart('container', {
      chart: {
       plotBackgroundColor: null,
       plotBorderWidth: null,
       plotShadow: false,
       type: 'pie'
      },
      title: {
       text: 'Late and on time data'
      },
      plotOptions: {
       pie: {
        allowPointSelect: true,
        cursor: 'pointer',
        dataLabels: {
         enabled: false
        },
        showInLegend: true
       }
      },
      series: [{
       data: #{@chart_data.to_json}
      }]
     });
  

app/views/dashboard/index.html.haml
%h1 Dashboard

.row
  .col-sm-12
    .alert.alert-warning
      %strong
        No. of Late User today 
      %span.badge=@stats[:nos_of_late_users_today]
      .pull-right  
        %strong
          Average time for all users
        %span.badge=@stats[:avg_time]


%table.table.table-bordered
  %tr
    %td Name
    %td Arrival Time
    %td Date
    %td Actions

  -@timelogs.each do |timelog|
    %tr{class: "#{(timelog.is_late) ? 'danger' : ''}"}
      %td=link_to timelog.username, user_dashboard_path(timelog.user_id)
      %td=timelog.login_time.strftime("%H:%M")
      %td=timelog.login_time.strftime("%d-%b-%y")
      %td=link_to "Destroy", users_path(timelog.user_id), method: :delete, data: {confirm: "Are you sure?"}

= will_paginate @timelogs

= render partial: "charts"

app/views/dashboard/user.html.haml
%h1= "Dashboard for User: #{@user.name} "

.row
  .col-sm-12
    .alert.alert-warning
      %strong
        Average time for 
      %span.badge=@stats[:avg_time]


%table.table.table-bordered
  %tr
    %td Arrival Time
    %td Date

  -@timelogs.each do |timelog|
    %tr{class: "#{(timelog.is_late) ? 'danger' : ''}"}
      %td=timelog.login_time.strftime("%H:%M")
      %td=timelog.login_time.strftime("%d-%b-%y")

= will_paginate @timelogs

= render partial: "charts"

app/views/landing/index.html.haml
.row
  .col-sm-6
    .panel.panel-default
      .panel-body
        =link_to "Create new User", new_users_path, class: "btn btn-primary"
        - if current_admin_user
          = link_to "Admin Logout", destroy_admin_user_session_path, class: "btn btn-danger pull-right", method: :delete
          = link_to "Dashboard", dashboard_path, class: "btn btn-warning pull-right"
        -else    
          = link_to "Admin Login", new_admin_user_session_path, class: "btn btn-info pull-right"
        %hr
        = form_for(@timelog, class: "form-inline") do |f|
          = text_field_tag "username", nil, class: "form-control", placeholder: "User name to log in", required: true

app/views/layouts/_messages.html.haml
- if notice
  .alert.alert-success
    =notice
- if flash[:error]
  .alert.alert-danger
    = flash[:error]

-[@user, @timelog].each do |data|
  - next unless data && data.errors.any?
  .alert.alert-danger
    %h2= "#{pluralize(data.errors.count, "error")} prohibited this user from being saved:"
    %ul
      - data.errors.full_messages.each do |msg|
        %li= msg

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Geni
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container
      = render partial: "layouts/messages"
      = yield
  = javascript_include_tag 'application', 'data-turbolinks-track' => true    

app/views/timelogs/_form.html.haml
= form_for @timelog do |f|
  - if @timelog.errors.any?
    #error_explanation
      %h2= "#{pluralize(@timelog.errors.count, "error")} prohibited this timelog from being saved:"
      %ul
        - @timelog.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/timelogs/edit.html.haml
%h1 Editing timelog

= render 'form'

= link_to 'Show', @timelog
\|
= link_to 'Back', timelogs_path

app/views/timelogs/index.html.haml
%h1 Listing timelogs

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @timelogs.each do |timelog|
      %tr
        %td= link_to 'Show', timelog
        %td= link_to 'Edit', edit_timelog_path(timelog)
        %td= link_to 'Destroy', timelog, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Timelog', new_timelog_path

app/views/timelogs/new.html.haml
%h1 New timelog

= render 'form'

= link_to 'Back', root_url

app/views/timelogs/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_timelog_path(@timelog)
\|
= link_to 'Back', timelogs_path

app/views/users/_form.html.haml
.row
  .col-sm-12
    = form_for(@user, class: "form-inline") do |f|
      = f.text_field :name, class: "form-control", placeholder: "Name"
      .actions
        = f.submit 'Save', class: "btn btn-primary"

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', root_url